[build]
  command = "echo 'hi'"
  publish = "fixtures/publishDir"
  functions = "fixtures/functions"

[[plugins]]
  package = "./index.js"
  [plugins.inputs]
    exclude = ['/search.html']
    debugMode = true